In [1]:
import numpy as np
import yaml

In [2]:
#yaml_file = "omni-radtan/camchain-2019-06-11-14-36-07.yaml"
yaml_file = "omni-radtan/camchain-2019-06-20-14-29-45.yaml"
with open(yaml_file, 'r') as stream:
    try:
        data = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

In [3]:
T10 = np.array(data['cam1']['T_cn_cnm1'])

In [4]:
T10

array([[-9.99963565e-01, -3.95477740e-03,  7.56491213e-03,
         6.34342183e-03],
       [-3.94781603e-03,  9.99991770e-01,  9.34929409e-04,
         1.10663990e-02],
       [-7.56854731e-03,  9.05030463e-04, -9.99970949e-01,
        -1.41873130e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [5]:
T21 = np.array(data['cam2']['T_cn_cnm1'])

In [6]:
T21

array([[ 0.99991645, -0.0105854 , -0.00741907, -0.35474456],
       [-0.00706073,  0.03349753, -0.99941386,  0.00157114],
       [ 0.01082771,  0.99938274,  0.03341999, -0.01977093],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
T32 = np.array(data['cam3']['T_cn_cnm1'])

In [8]:
T32

array([[-9.99285650e-01,  2.11578374e-02, -3.13135057e-02,
        -9.67659165e-04],
       [ 2.11413644e-02,  9.99776129e-01,  8.57099214e-04,
        -9.49595142e-03],
       [ 3.13246298e-02,  1.94476712e-04, -9.99509244e-01,
        -2.81627617e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [9]:
np.linalg.norm(T10[0:3,3])

0.01907836569247337

In [10]:
np.linalg.norm(T21[0:3,3])

0.3552985571545823

In [11]:
np.linalg.norm(T32[0:3,3])

0.029736351563700143

In [12]:
from tf.transformations import quaternion_from_matrix, euler_from_matrix

In [13]:
quaternion_from_matrix(T10)

array([-1.97566656e-03,  9.99990785e-01,  4.59994207e-04,  3.78339972e-03])

In [14]:
np.array(euler_from_matrix(T10))*180/np.pi

array([ 179.94814408,    0.43364996, -179.77379974])

In [15]:
quaternion_from_matrix(T21)

array([ 0.69516166, -0.00634605,  0.00122584,  0.71882438])

In [16]:
np.array(euler_from_matrix(T21))*180/np.pi

array([88.08470664, -0.62039428, -0.40457698])

In [17]:
quaternion_from_matrix(T32)

array([ 1.05766899e-02,  9.99821362e-01,  2.62940953e-04, -1.56623318e-02])

In [18]:
np.array(euler_from_matrix(T32))*180/np.pi

array([179.98885183,  -1.79506273, 178.78800394])