In [1]:
import numpy as np
import yaml
from tf.transformations import quaternion_from_matrix, euler_from_matrix

In [2]:
yaml_file = "calibration/omni-radtan/camchain-stereo_2019-07-05-08-24-01.yaml"
with open(yaml_file, 'r') as stream:
    try:
        data = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

#### Camera topics and overlaps

In [3]:
data['cam0']['rostopic'], data['cam0']['cam_overlaps']

('/bottom/back/image_raw', [2, 3])

In [4]:
data['cam1']['rostopic'], data['cam1']['cam_overlaps']

('/bottom/front/image_raw', [2, 3])

In [5]:
data['cam2']['rostopic'], data['cam2']['cam_overlaps']

('/top/back/image_raw', [0, 1])

In [6]:
data['cam3']['rostopic'], data['cam3']['cam_overlaps']

('/top/front/image_raw', [0, 1])

#### Transformations between camera frames

In [7]:
T10 = np.array(data['cam1']['T_cn_cnm1'])

In [8]:
T21 = np.array(data['cam2']['T_cn_cnm1'])

In [9]:
T32 = np.array(data['cam3']['T_cn_cnm1'])

Translations

In [10]:
T10[0:3,3]

array([ 0.0012639 , -0.00071856, -0.01283623])

In [11]:
np.linalg.norm(_)

0.012918301713276134

In [12]:
T21[0:3,3]

array([-0.00971141,  0.34765956, -0.00541575])

In [13]:
np.linalg.norm(_)

0.34783733505676839

In [14]:
T32[0:3,3]

array([-0.00085367,  0.00056016, -0.01669864])

In [15]:
np.linalg.norm(_)

0.016729824978133793

Rotations

In [16]:
print(quaternion_from_matrix(T10))
print(np.array(euler_from_matrix(T10))*180/np.pi)

[ 0.00243342  0.99996023  0.00787076 -0.0034159 ]
[ 179.09900751   -0.39361604  179.72423452]


In [17]:
print(quaternion_from_matrix(T21))
print(np.array(euler_from_matrix(T21))*180/np.pi)

[ 0.00183455 -0.6971804  -0.00310491  0.71688666]
[ 14.02005846 -88.35377811 -14.1230048 ]


In [18]:
print(quaternion_from_matrix(T32))
print(np.array(euler_from_matrix(T32))*180/np.pi)

[ 0.0020117   0.99998409 -0.00419444 -0.00319189]
[-179.51860846   -0.3647934   179.76794068]
