In [1]:
import numpy as np
import yaml

In [2]:
yaml_file = "omni-radtan/camchain-2019-06-03-14-19-47.yaml"
with open(yaml_file, 'r') as stream:
    try:
        data = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

In [3]:
T10 = np.array(data['cam1']['T_cn_cnm1'])

In [4]:
T10

array([[-0.99997349,  0.00678417, -0.00264529,  0.00733637],
       [ 0.00676753,  0.99995757,  0.00624895,  0.00134343],
       [ 0.00268757,  0.00623088, -0.99997698, -0.014835  ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
T21 = np.array(data['cam2']['T_cn_cnm1'])

In [6]:
T21

array([[ 0.14134827, -0.12516883, -0.98201498,  0.02932938],
       [-0.06850371, -0.99083333,  0.11643261,  0.35222602],
       [-0.98758691,  0.05081412, -0.14862711, -0.01130358],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
T32 = np.array(data['cam3']['T_cn_cnm1'])

In [8]:
T32

array([[-0.99993342, -0.00814224, -0.00817665,  0.01464751],
       [-0.00804485,  0.99989714, -0.01187373,  0.00576277],
       [ 0.00827249, -0.01180716, -0.99989607, -0.01160258],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [9]:
np.linalg.norm(T10[0:3,3])

0.01660434713443134

In [10]:
np.linalg.norm(T21[0:3,3])

0.3536257191031884

In [11]:
np.linalg.norm(T32[0:3,3])

0.01955451372182338

In [12]:
from tf.transformations import quaternion_from_matrix

In [13]:
quaternion_from_matrix(T10)

array([ 0.00338796,  0.9999885 ,  0.00311999, -0.00133323])

In [14]:
quaternion_from_matrix(T21)

array([ 0.75511733, -0.06412002, -0.65208472, -0.0217246 ])

In [15]:
quaternion_from_matrix(T32)

array([-0.00404691,  0.99996583, -0.00592043, -0.00411243])