In [1]:
import numpy as np
import yaml

In [2]:
yaml_file = "omni-radtan/camchain-2019-06-11-14-36-07.yaml"
with open(yaml_file, 'r') as stream:
    try:
        data = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

In [3]:
T10 = np.array(data['cam1']['T_cn_cnm1'])

In [4]:
T10

array([[-0.99991018,  0.00877535,  0.0101307 ,  0.0032775 ],
       [ 0.00847046,  0.9995213 , -0.02975616, -0.00130215],
       [-0.01038697, -0.02966768, -0.99950585, -0.02072771],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
T21 = np.array(data['cam2']['T_cn_cnm1'])

In [6]:
T21

array([[-0.03509369, -0.01369781, -0.99929015, -0.01086023],
       [ 0.00963515, -0.99986423,  0.0133673 ,  0.35121368],
       [-0.99933758, -0.00915921,  0.0352209 ,  0.0032623 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
T32 = np.array(data['cam3']['T_cn_cnm1'])

In [8]:
T32

array([[-0.99999235,  0.00365672,  0.00138671,  0.00288547],
       [ 0.00366567,  0.9999721 ,  0.00650879, -0.00247557],
       [-0.00136287,  0.00651383, -0.99997786, -0.00848798],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [9]:
np.linalg.norm(T10[0:3,3])

0.02102559477741972

In [10]:
np.linalg.norm(T21[0:3,3])

0.35139669342511726

In [11]:
np.linalg.norm(T32[0:3,3])

0.009300547027420905

In [12]:
from tf.transformations import quaternion_from_matrix, euler_from_matrix

In [13]:
quaternion_from_matrix(T10)

array([ 0.00431203,  0.99986716, -0.01485793,  0.0051301 ])

In [14]:
np.array(euler_from_matrix(T10))*180/np.pi

array([-178.29982614,    0.5951405 ,  179.51464625])

In [15]:
quaternion_from_matrix(T21)

array([-0.69454115,  0.00146235,  0.7194058 ,  0.00810841])

In [16]:
np.array(euler_from_matrix(T21))*180/np.pi

array([-14.57691615,  87.91441149, 164.64744498])

In [17]:
quaternion_from_matrix(T32)

array([1.83060880e-03, 9.99992788e-01, 3.25567880e-03, 6.87399604e-04])

In [18]:
np.array(euler_from_matrix(T32))*180/np.pi

array([1.79626782e+02, 7.80866972e-02, 1.79789972e+02])