In [1]:
import numpy as np
import yaml

In [2]:
yaml_file = "omni-radtan/camchain-2019-06-03-10-51-37.yaml"
with open(yaml_file, 'r') as stream:
    try:
        data = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

In [3]:
T10 = np.array(data['cam1']['T_cn_cnm1'])

In [4]:
T10

array([[-0.99999284,  0.00356509, -0.00126858, -0.01153935],
       [ 0.00357726,  0.99994628, -0.00972822,  0.01331764],
       [ 0.00123383, -0.00973269, -0.99995188, -0.01033976],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
T21 = np.array(data['cam2']['T_cn_cnm1'])

In [6]:
T21

array([[ 0.17827976, -0.15575294, -0.97157468,  0.01853026],
       [-0.0954801 , -0.98547165,  0.14046058,  0.35105225],
       [-0.97933645,  0.06772477, -0.19056095, -0.04214539],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
T32 = np.array(data['cam3']['T_cn_cnm1'])

In [8]:
T32

array([[-0.9998847 ,  0.00314291,  0.01485615, -0.00262439],
       [ 0.00282003,  0.99976045, -0.02170461, -0.0050092 ],
       [-0.01492081, -0.02166021, -0.99965404, -0.02910539],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [9]:
np.linalg.norm(T10[0:3,3])

0.020431024590730446

In [10]:
np.linalg.norm(T21[0:3,3])

0.3540583068997997

In [11]:
np.linalg.norm(T32[0:3,3])

0.02964967539342462

In [12]:
from tf.transformations import quaternion_from_matrix

In [14]:
quaternion_from_matrix(T10)

array([ 1.78561064e-03,  9.99986374e-01, -4.86529579e-03, -6.25608771e-04])

In [15]:
quaternion_from_matrix(T21)

array([ 0.76718843, -0.0818681 , -0.63573401, -0.02370207])

In [16]:
quaternion_from_matrix(T32)

array([ 0.00149087,  0.9999124 , -0.01084215,  0.00744489])